#
# Copyright 2017 LinkedIn Corporation. All rights reserved. Licensed under the BSD-2 Clause license.
# See LICENSE in the project root for license information.
#

logging:
  level:
    com.linkedin: DEBUG

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

user:
  login: user
  password: password